[tox]
envlist = lint, unittest
skipsdist = True

[testenv:lint]
deps =
    -rrequirements/requirements_lint.txt
commands =
    flake8 . --count --show-source --statistics
    python scripts/check_filenames.py

[testenv:unittest]
deps =
    -rrequirements/requirements_test.txt
commands =
    python -c "print('No tests yet.')"

[flake8]
max-line-length = 140
inline-quotes = single
multiline-quotes = single
docstring-quotes = single
import-order-style = smarkets
exclude =
    .git,
    .tox,
    .venv,
    __pycache__,
    __init__.py
