[tox]
envlist = lint, unittest
skipsdist = True

[testenv:lint]
deps =
    -rrequirements/requirements_lint.txt
commands =
    flake8 .
    python scripts/check_filenames.py

[testenv:unittest]
deps =
    -rrequirements/requirements_test.txt
commands =
    coverage run -m unittest discover -s tests
    coverage report -m

[flake8]
max-line-length = 140
inline-quotes = single
multiline-quotes = single
docstring-quotes = single
import-order-style = smarkets
exclude =
    .git,
    .tox,
    __pycache__,
    build,
    dist
