'''HomeIotManager - 定数定義モジュール

システム内で使用される動作パラメータ・数値を一括管理します。
'''

CHECK_INTERVAL_SECONDS = 10
OUT_THRESHOLD_SECONDS = 300
HUE_THRESHOLD_SECONDS = 600
LAST_IN_THRESHOLD_SECONDS = 180

HUE_ON_BEGIN_HOUR = 17
HUE_ON_END_HOUR = 6
ROOMY_SLEEP_START_HOUR = 22
ROOMY_SLEEP_END_HOUR = 6

HUE_ON_GROUP_ID = '2'
HUE_OFF_GROUP_ID = '3'

WEB_PORT = 8930
