name: CI

on:
  pull_request:

.job_template: &job_template
  runs-on: ubuntu-latest

jobs:
  lint:
    <<: *job_template
    steps:
      - name: Set up environment
        uses: ./.github/actions/setup-python-env
      - name: Run lint
        run: tox -e lint

  unittest:
    <<: *job_template
    steps:
      - name: Set up environment
        uses: ./.github/actions/setup-python-env
      - name: Run unittest
        run: tox -e unittest
