name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up environment
        uses: ./.github/actions/setup-python-env

      - name: Run lint
        run: tox -e lint

  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up environment
        uses: ./.github/actions/setup-python-env

      - name: Run unittest
        run: tox -e unittest
